# Generated by Django 3.1 on 2020-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
