# Generated by Django 3.1 on 2020-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_auto_20200824_1401'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'substitute'), name='unique_combination'),
        ),
        migrations.AlterModelTable(
            name='favorites',
            table='favorites_favorites',
        ),
    ]
